from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()

class Monster(Base):
    __tablename__ = "monsters"
    
    id = Column(Integer, primary_key = True)
    cleanName = Column(String)
    translatedName = Column(String)
    internationalName = Column(String)
    level = Column(Integer)
    hp = Column(Integer)
    sp = Column(Integer)
    baseExp = Column(Integer)
    jobExp = Column(Integer)
    atkMin = Column(Integer)
    atkMax = Column(Integer)
    physicalDef = Column(Integer)
    magicDef = Column(Integer)
    str = Column(Integer)
    agi = Column(Integer)
    vit = Column(Integer)
    int = Column(Integer)
    dex = Column(Integer)
    luk = Column(Integer)
    attackType = Column(Integer)
    skillRange = Column(Integer)
    sightRange = Column(Integer)
    scale = Column(Integer)
    race = Column(Integer)
    element = Column(Integer)
    mode = Column(Integer)
    speed = Column(Integer)
    attackDelay = Column(Integer)
    attackAnimation = Column(Integer)
    damageAnimation = Column(Integer)
    mvpExp = Column(Integer)
    mvpBonusExp = Column(Integer)
    mvpdropID1 = Column(Integer)
    mvpdropRate1 = Column(Integer)
    mvpdropID2 = Column(Integer)
    mvpdropRate2 = Column(Integer)
    mvpdropID3 = Column(Integer)
    mvpdropRate3 = Column(Integer)
    dropID1 = Column(Integer)
    dropRate1 = Column(Integer)
    dropID2 = Column(Integer)
    dropRate2 = Column(Integer)
    dropID3 = Column(Integer)
    dropRate3 = Column(Integer)
    dropID4 = Column(Integer)
    dropRate4 = Column(Integer)
    dropID5 = Column(Integer)
    dropRate5 = Column(Integer)
    dropID6 = Column(Integer)
    dropRate6 = Column(Integer)
    dropID6 = Column(Integer)
    dropRate7 = Column(Integer)
    dropID8 = Column(Integer)
    dropRate8 = Column(Integer)
    dropID9 = Column(Integer)
    dropRate9 = Column(Integer)
    dropCardID = Column(Integer)
    

