-record(ids,
        {key,
         id}).
-record(char,
        {id,
         num = 0,
         name = "",
         job = 0,
         base_level = 1,
         base_exp = 0,
         job_level = 1,
         job_exp = 0,
         zeny = 0,
         str = 1,
         agi = 1,
         vit = 1,
         int = 1,
         dex = 1,
         luk = 1,
         max_hp = 42,
         hp = 42,
         max_sp = 11,
         sp = 11,
         status_points = 0,
         skill_points = 0,
         hair_style = 0,
         hair_colour = 0,
         clothes_colour = 0,
         view_weapon = 0,
         view_shield = 0,
         view_head_top = 0,
         view_head_middle = 0,
         view_head_bottom = 0,
         map = "new_1-1",
         x = 0,
         y = 0,
         save_map = "new_1-1",
         save_x = 0,
         save_y = 0,
         online = false,
         fame = 0,
         guild_position = 0,
         guild_taxed = 0,
         account_id = 0,
         party_id = 0,
         guild_id = 0,
         pet_id = 0,
         homunculus_id = 0,
         mercenary_id = 0}).
-record(account,
        {id,
         login,
         password,
         email,
         gender = 0,
         login_count = 0,
         last_login,
         last_ip,
         gm_level = 0,
         ban_until}).
-record(apiresponse,
        {msg,
         info,
         account,
         char}).
-record(apirequest,
        {key,
         node,
         add_account,
         get_account,
         delete_account,
         update_account,
         add_char,
         get_char,
         delete_char,
         update_char}).
