DROP TABLE IF EXISTS `characters`;
CREATE TABLE `characters` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `accountID` int(11) unsigned NOT NULL default 0,
  `charNum` tinyint(1) NOT NULL default 0,
  `name` varchar(30) NOT NULL,
  `job` smallint(6) unsigned NOT NULL default 0,
  `baseLevel` smallint(6) unsigned NOT NULL default 1,
  `baseExp` bigint(20) unsigned NOT NULL default 0,
  `jobLevel` smallint(6) unsigned NOT NULL default 1,
  `jobExp` bigint(20) unsigned NOT NULL default 0,
  `zeny` int(11) unsigned NOT NULL default 0,
  `str` smallint(4) unsigned NOT NULL default 0,
  `agi` smallint(4) unsigned NOT NULL default 0,
  `vit` smallint(4) unsigned NOT NULL default 0,
  `int` smallint(4) unsigned NOT NULL default 0,
  `dex` smallint(4) unsigned NOT NULL default 0,
  `luk` smallint(4) unsigned NOT NULL default 0,
  `maxHP` mediumint(8) unsigned NOT NULL default 0,
  `hp` mediumint(8) unsigned NOT NULL default 0,
  `maxSP` mediumint(6) unsigned NOT NULL default 0,
  `sp` mediumint(6) unsigned NOT NULL default 0,
  `statusPoints` smallint(4) unsigned NOT NULL default 0,
  `skillPoints` smallint(4) unsigned NOT NULL default 0,
  `partyID` int(11) unsigned NOT NULL default 0,
  `guildID` int(11) unsigned NOT NULL default 0,
  `petID` int(11) unsigned NOT NULL default 0,
  `homunculusID` int(11) unsigned NOT NULL default 0,
  `hairStyle` tinyint(4) unsigned NOT NULL default 0,
  `hairColor` smallint(5) unsigned NOT NULL default 0,
  `clothesColor` smallint(5) unsigned NOT NULL default 0,
  `viewWeapon` smallint(6) unsigned NOT NULL default 1,
  `viewShield` smallint(6) unsigned NOT NULL default 0,
  `viewHeadTop` smallint(6) unsigned NOT NULL default 0,
  `viewHeadMiddle` smallint(6) unsigned NOT NULL default 0,
  `viewHeadBottom` smallint(6) unsigned NOT NULL default 0,
  `map` varchar(20) NOT NULL default 'new_zone01',
  `x` smallint(4) unsigned NOT NULL default '53',
  `y` smallint(4) unsigned NOT NULL default '111',
  `saveMap` varchar(20) NOT NULL default 'new_zone01',
  `saveX` smallint(4) unsigned NOT NULL default '53',
  `saveY` smallint(4) unsigned NOT NULL default '111',
  `online` tinyint(2) NOT NULL default 0,
  `fame` int(11) unsigned NOT NULL default 0,
  PRIMARY KEY  (`id`),
  KEY `partyID` (`partyID`),
  KEY `guildID` (`guildID`),
  KEY `name` (`name`),
  KEY `online` (`online`)
) AUTO_INCREMENT=150000;

DROP TABLE IF EXISTS `accounts`;
CREATE TABLE `accounts` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `username` varchar(255) NOT NULL,
  `password` varchar(40) NOT NULL,
  `Email` varchar(60) NOT NULL,
  `gender` tinyint(1) NOT NULL default 1,
  `loginCount` mediumint(9) unsigned NOT NULL default 0,
  `lastLogin` datetime NULL,
  `lastIP` varchar(100) NULL,
  `gmLevel` tinyint(2) NOT NULL default 0,
  `banUntil` datetime NULL,
  PRIMARY KEY (`id`),
  KEY `username` (`username`)
) AUTO_INCREMENT=2000000;
